import { DoctorsService } from './doctor/doctors.service';
export { SettingsService } from './settings/settings.service';
export { SidebarService } from './shared/sidebar.service';
export { SharedService } from './shared/shared.service';
export { UserService } from './user/user.service';
export { HospitalService } from './hospital/hospital.service';
export { DoctorsService } from './doctor/doctors.service';
export { UploadFileService } from './upload/upload-file.service';
export { LoginGuard } from './guards/login.guard';
